version: 1.0.{build}
branches:
  only:
  - master

image: Visual Studio 2022
configuration: Release
platform: Any CPU
nuget:
  project_feed: true
build:
  project: '\Src\Serilog.Sinks.GraylogGelf\Serilog.Sinks.GraylogGelf.csproj'
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: '*\*.dll'
  name: Serilog.Sinks.GraylogGelf
deploy:
- provider: GitHub
  auth_token:
    secure: F/19bv2TYoeZ5LhzsKZUeVYgpbI53wUcX8RSHE9+T8CD1Q6tXF+3IBU5xe2YyQQx
  artifact: Serilog.Sinks.GraylogGelf
  on:
    branch: master
- provider: NuGet
  api_key:
    secure: v761W1/T2FLgfDsvdfcLKlQSiutFvocnjwTwig7aNOSB3k9ssE5DG/37t5ejQ5lC
  on:
    branch: master
