version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - develop
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  project_feed: true
  disable_publish_on_pr: true
before_build:
- ps: dotnet restore
build:
  project: ./BlazorSortableList.Lib/BlazorSortableList.csproj
  publish_nuget: true
  verbosity: minimal
notifications:
- provider: Email
  to:
  - alexnek@russinger.com
  subject: Build failure Blazor sortable list
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false